name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Determine Core Repository
      uses: frabert/replace-string-action@master
      id: core-repository
      with:
        pattern: '(.*)-android-map'
        string: "${{ github.repository }}"
        replace-with: '$1-core-java'
    - name: Checkout Core Repository
      uses: actions/checkout@v1
      with:
        repository: ${{ steps.core-repository.outputs.replaced }}
        ref: ${{ github.ref }}
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build & Install Core
      run: mvn -f ../geopackage-core-java clean install -DskipTests
    - name: Determine Android Repository
      uses: frabert/replace-string-action@master
      id: android-repository
      with:
        pattern: '(.*)-android-map'
        string: "${{ github.repository }}"
        replace-with: '$1-android'
    - name: Checkout Android Repository
      uses: actions/checkout@v1
      with:
        repository: ${{ steps.android-repository.outputs.replaced }}
        ref: ${{ github.ref }}
    - name: Build Android with Gradle
      working-directory: ../geopackage-android
      run: ./gradlew uploadArchives -x lint
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Build with Gradle
      run: ./gradlew build -x lint
